import type { Model, PhotoInput } from "../schema";

/**
 * Necta snack, food and cold-can machines.
 *
 * Snakky's figures come from its archived service manual, which carries more
 * detail than the marketing page ever did - ambient tolerance, fuse rating and
 * noise level included. The rest come from refurbished-dealer listings.
 */

type Draft = Omit<
  Model,
  "spec" | "recommendation" | "photos" | "cabinetOf" | "coffeeUnit" | "condition"
> & {
  /** Set only where a variant differs from its base model behind the panel. */
  cabinetOf?: string | null;
  /** Set only on machines supplied new. Omitted is refurbished, which is most
   *  of the stock - see `schema.ts`. */
  condition?: Model["condition"];
} & {
  spec?: Partial<Model["spec"]>;
  recommendation?: Partial<Model["recommendation"]>;
  /** Empty until this model is photographed; see docs/catalogue.md. */
  photos?: PhotoInput[];
};

export const nectaSnack: Draft[] = [
  {
    id: "snakky",
    slug: "necta-snakky",
    photos: [
      {
        src: "/machines/necta-snakky/front.png",
        alt: "Снакс автомат Necta Snakky, изглед отпред",
        view: "front",
        credit: "Фабрично изображение на производителя",
      },
    ],
    name: "Necta Snakky",
    manufacturer: "necta",
    category: "snack",
    currentName: null,
    specSource: "Necta Snakky service manual ed.2 H180U01 (архив)",
    intro:
      "Най-разпространеният снакс автомат в България. Компактен, надежден, с широко достъпни части.",
    spec: {
      userInterface: "Бутони",
      heightMm: 1700,
      widthMm: 701,
      depthMm: 853,
      depthOpenMm: 1335,
      weightKg: 190,
      voltage: "230 V",
      maxPowerW: 345,
      frequencyHz: 50,
      numTrays: 6,
      dispensingSystem: "Спирали",
      temperature: "8-20 °C",
      configuration: "Снаксове, кутии и бутилки",
    },
    recommendation: {
      venueTypes: ["office", "manufacturing", "car-service", "car-wash", "gym"],
      minHeadcount: 20,
      maxHeadcount: 80,
      dailyCapacity: 80,
      shifts: [1, 2],
      products: ["snack", "cold"],
    },
  },
  {
    id: "snakky-max",
    slug: "necta-snakky-max",
    photos: [
      {
        src: "/machines/necta-snakky-max/front.png",
        alt: "Снакс автомат Necta Snakky Max, изглед отпред",
        view: "front",
        credit: "Фабрично изображение на производителя",
      },
    ],
    name: "Necta Snakky Max",
    manufacturer: "necta",
    category: "snack",
    currentName: null,
    specSource: "Дилърски спецификации (Vending Systems, VendingOutlet)",
    intro:
      "По-високата Snakky с 300 продукта. Еднаква на височина с Kikko Max, така че двете застават една до друга без разлика в силуета.",
    spec: {
      userInterface: "Бутони",
      heightMm: 1830,
      widthMm: 735,
      depthMm: 855,
      depthOpenMm: 1350,
      weightKg: 225,
      voltage: "230 V",
      frequencyHz: 50,
      numTrays: 7,
      dispensingSystem: "Спирали",
      productCapacity: 300,
      configuration: "Снаксове, кутии и бутилки",
    },
    recommendation: {
      venueTypes: ["manufacturing", "warehouse", "logistics", "school", "gym"],
      minHeadcount: 50,
      maxHeadcount: 150,
      dailyCapacity: 140,
      shifts: [2, 3],
      products: ["snack", "cold"],
    },
  },
  {
    id: "snakky-sl",
    slug: "necta-snakky-sl",
    photos: [
      {
        src: "/machines/necta-snakky-sl/front.png",
        alt: "Снакс автомат Necta Snakky SL, изглед отпред",
        view: "front",
        credit: "Фабрично изображение на производителя",
      },
    ],
    name: "Necta Snakky SL",
    manufacturer: "necta",
    category: "snack",
    currentName: null,
    specSource: "Necta продуктова документация",
    intro:
      "Подчинена машина без собствено табло. Свързва се към водеща машина и разширява избора, без да заема второ платежно устройство.",
    spec: {
      userInterface: "Без табло (подчинена машина)",
      heightMm: 1700,
      widthMm: 701,
      depthMm: 853,
      voltage: "230 V",
      dispensingSystem: "Спирали",
    },
    recommendation: {
      venueTypes: ["manufacturing", "warehouse", "logistics"],
      minHeadcount: 60,
      maxHeadcount: 200,
      dailyCapacity: 80,
      shifts: [2, 3],
      products: ["snack", "cold"],
    },
  },
  {
    id: "sfera",
    slug: "necta-sfera",
    photos: [
      {
        src: "/machines/necta-sfera/front.png",
        alt: "Снакс автомат Necta Sfera, изглед отпред",
        view: "front",
        credit: "Фабрично изображение на производителя",
      },
    ],
    name: "Necta Sfera",
    manufacturer: "necta",
    category: "snack",
    currentName: null,
    specSource: "Дилърски спецификации (VendTrade, VendingOutlet)",
    intro:
      "Широка машина с голяма витрина и висок капацитет. За обекти със сериозен поток хора.",
    spec: {
      userInterface: "Бутони",
      heightMm: 1850,
      widthMm: 1000,
      depthMm: 920,
      weightKg: 320,
      voltage: "230 V",
      maxPowerW: 510,
      numTrays: 6,
      dispensingSystem: "Спирали (до 8 на рафт)",
      temperature: "5 °C",
    },
    recommendation: {
      venueTypes: ["manufacturing", "logistics", "school", "hospital", "retail"],
      minHeadcount: 100,
      maxHeadcount: 300,
      dailyCapacity: 200,
      shifts: [2, 3],
      products: ["snack", "cold", "food"],
    },
  },
  {
    id: "melodia",
    slug: "necta-melodia",
    photos: [
      {
        src: "/machines/necta-melodia/front.png",
        alt: "Снакс автомат Necta Melodia, изглед отпред",
        view: "front",
        credit: "Фабрично изображение на производителя",
      },
    ],
    name: "Necta Melodia",
    manufacturer: "necta",
    category: "snack",
    currentName: null,
    specSource: "Дилърски спецификации (RatioVending, VendTrade)",
    intro:
      "Компактна по височина машина за места с ограничено пространство. 27 селекции и до 344 продукта.",
    spec: {
      userInterface: "Сензорна клавиатура",
      numberOfSelections: 27,
      widthMm: 717,
      voltage: "230 V",
      dispensingSystem: "Спирали",
      productCapacity: 344,
    },
    recommendation: {
      venueTypes: ["office", "car-service", "retail", "gym", "school"],
      minHeadcount: 25,
      maxHeadcount: 90,
      dailyCapacity: 100,
      shifts: [1, 2],
      products: ["snack"],
    },
  },
  {
    id: "rondo",
    slug: "necta-rondo",
    photos: [
      {
        src: "/machines/necta-rondo/front.png",
        alt: "Снакс автомат Necta Rondo, изглед отпред",
        view: "front",
        credit: "Фабрично изображение на производителя",
      },
    ],
    name: "Necta Rondo",
    manufacturer: "necta",
    category: "snack",
    currentName: null,
    specSource: "Vendtrade продуктова страница",
    intro:
      "Машина с голяма витрина и регулируеми рафтове - снаксове, кутии и бутилки в една клетка. Клавиатура с 12 бутона и 5 бутона за директен избор.",
    spec: {
      userInterface: "Цифрова клавиатура с 12 бутона и 5 директни избора",
      numberOfSelections: 40,
      heightMm: 1830,
      widthMm: 880,
      depthMm: 890,
      voltage: "230 V",
      numTrays: 6,
      dispensingSystem: "Регулируеми рафтове",
      configuration: "Снаксове, кутии и бутилки",
    },
    recommendation: {
      venueTypes: ["manufacturing", "hospital", "school"],
      minHeadcount: 40,
      maxHeadcount: 150,
      dailyCapacity: 120,
      shifts: [2, 3],
      products: ["snack", "cold"],
    },
  },
  {
    id: "samba",
    slug: "necta-samba",
    photos: [
      {
        src: "/machines/necta-samba/front.png",
        alt: "Снакс автомат Necta Samba, изглед отпред",
        view: "front",
        credit: "Фабрично изображение на производителя",
      },
    ],
    name: "Necta Samba",
    manufacturer: "necta",
    category: "snack",
    currentName: null,
    specSource: "Дилърски спецификации (VendTrade, Bitesize Vending)",
    intro:
      "Голяма машина с до седем рафта. Управлява три температурни зони в една клетка.",
    spec: {
      userInterface: "Бутони",
      heightMm: 1830,
      widthMm: 890,
      depthMm: 860,
      weightKg: 275,
      voltage: "230 V",
      numTrays: 7,
      dispensingSystem: "Спирали (до 8 на рафт)",
      configuration: "Снаксове, кутии, бутилки и храна",
    },
    recommendation: {
      venueTypes: ["manufacturing", "warehouse", "logistics", "hospital"],
      minHeadcount: 80,
      maxHeadcount: 250,
      dailyCapacity: 180,
      shifts: [2, 3],
      products: ["snack", "cold", "food"],
    },
  },
  {
    id: "samba-top",
    slug: "necta-samba-top",
    cabinetOf: "samba",
    photos: [
      {
        src: "/machines/necta-samba-top/front.png",
        alt: "Снакс автомат Necta Samba Top, изглед отпред",
        view: "front",
        credit: "Фабрично изображение на производителя",
      },
    ],
    name: "Necta Samba Top",
    manufacturer: "necta",
    category: "snack",
    currentName: null,
    specSource: "Вариант на Samba - общ корпус",
    intro: "Samba в конфигурация Top, с по-висок клас оборудване.",
    spec: {
      userInterface: "Бутони",
      heightMm: 1830,
      widthMm: 890,
      depthMm: 860,
      weightKg: 275,
      voltage: "230 V",
      numTrays: 7,
      dispensingSystem: "Спирали (до 8 на рафт)",
    },
    recommendation: {
      venueTypes: ["manufacturing", "warehouse", "hospital", "business-centre"],
      minHeadcount: 80,
      maxHeadcount: 250,
      dailyCapacity: 180,
      shifts: [2, 3],
      products: ["snack", "cold", "food"],
    },
  },
  {
    id: "samba-top-lift",
    slug: "necta-samba-top-lift",
    cabinetOf: "samba",
    photos: [
      {
        src: "/machines/necta-samba-top-lift/front.png",
        alt: "Снакс автомат Necta Samba Top Lift с асансьор за доставка, изглед отпред",
        view: "front",
        credit: "Фабрично изображение на производителя",
      },
    ],
    name: "Necta Samba Top Lift",
    manufacturer: "necta",
    category: "snack",
    currentName: null,
    specSource: "Вариант на Samba - общ корпус, с асансьор",
    intro:
      "Samba Top с асансьор за доставка. Продуктът не пада, а се сваля - подходящо за чупливи и топли артикули.",
    spec: {
      userInterface: "Бутони",
      heightMm: 1830,
      widthMm: 890,
      depthMm: 860,
      weightKg: 275,
      voltage: "230 V",
      numTrays: 7,
      elevator: "Асансьор за доставка",
      dispensingSystem: "Спирали (до 8 на рафт)",
    },
    recommendation: {
      venueTypes: ["hospital", "business-centre", "hotel", "manufacturing"],
      minHeadcount: 80,
      maxHeadcount: 250,
      dailyCapacity: 180,
      shifts: [2, 3],
      products: ["snack", "cold", "food"],
    },
  },
  {
    id: "tango",
    slug: "necta-tango",
    photos: [
      {
        src: "/machines/necta-tango/front.png",
        alt: "Снакс автомат Necta Tango, изглед отпред",
        view: "front",
        credit: "Фабрично изображение на производителя",
      },
    ],
    name: "Necta Tango",
    manufacturer: "necta",
    category: "snack",
    currentName: "Gusto 8 Classic",
    specSource: "Дилърски спецификации (VendingOutlet, Oldham Vending)",
    intro:
      "Универсална машина за снаксове, храна, кутии и бутилки - или всичко наведнъж. До 56 селекции.",
    spec: {
      userInterface: "Бутони",
      numberOfSelections: 56,
      heightMm: 1830,
      widthMm: 890,
      depthMm: 870,
      weightKg: 280,
      voltage: "230 V",
      numTrays: 7,
      dispensingSystem: "Спирали (8 на рафт)",
      configuration: "Снаксове, захарни изделия, храна, кутии и бутилки",
    },
    recommendation: {
      venueTypes: ["manufacturing", "warehouse", "logistics", "school", "hospital"],
      minHeadcount: 80,
      maxHeadcount: 250,
      dailyCapacity: 200,
      shifts: [2, 3],
      products: ["snack", "cold", "food"],
    },
  },
  {
    id: "tango-food",
    slug: "necta-tango-food",
    cabinetOf: "tango",
    name: "Necta Tango Food",
    manufacturer: "necta",
    category: "snack",
    currentName: null,
    specSource: "Вариант на Tango - общ корпус, хранителна конфигурация",
    intro:
      "Tango в конфигурация за храна, с по-ниска работна температура.",
    spec: {
      userInterface: "Бутони",
      heightMm: 1830,
      widthMm: 890,
      depthMm: 870,
      weightKg: 280,
      voltage: "230 V",
      numTrays: 7,
      dispensingSystem: "Спирали (8 на рафт)",
      temperature: "0-4 °C (храна)",
      configuration: "Храна и снаксове",
    },
    recommendation: {
      venueTypes: ["manufacturing", "hospital", "logistics", "school"],
      minHeadcount: 80,
      maxHeadcount: 250,
      dailyCapacity: 200,
      shifts: [2, 3],
      products: ["food", "snack"],
    },
  },
  {
    id: "tango-top",
    slug: "necta-tango-top",
    cabinetOf: "tango",
    name: "Necta Tango Top",
    manufacturer: "necta",
    category: "snack",
    currentName: null,
    specSource: "Вариант на Tango - общ корпус",
    intro: "Tango в конфигурация Top.",
    spec: {
      userInterface: "Бутони",
      heightMm: 1830,
      widthMm: 890,
      depthMm: 870,
      weightKg: 280,
      voltage: "230 V",
      numTrays: 7,
      dispensingSystem: "Спирали (8 на рафт)",
    },
    recommendation: {
      venueTypes: ["manufacturing", "warehouse", "business-centre"],
      minHeadcount: 80,
      maxHeadcount: 250,
      dailyCapacity: 200,
      shifts: [2, 3],
      products: ["snack", "cold", "food"],
    },
  },
  {
    id: "swing",
    slug: "necta-swing",
    photos: [
      {
        src: "/machines/necta-swing/front.png",
        alt: "Снакс автомат Necta Swing, изглед отпред под ъгъл",
        view: "front",
        credit: "Фабрично изображение на производителя",
      },
    ],
    name: "Necta Swing",
    manufacturer: "necta",
    category: "snack",
    currentName: null,
    specSource: "Necta Swing operating manual (архив)",
    intro: "Машина за пакетирани продукти и напитки.",
    spec: { voltage: "230 V", dispensingSystem: "Спирали" },
    recommendation: {
      venueTypes: ["office", "car-service", "retail", "gym"],
      minHeadcount: 25,
      maxHeadcount: 90,
      dailyCapacity: 100,
      shifts: [1, 2],
      products: ["snack", "cold"],
    },
  },
];
